# Generated by Django 5.2.5 on 2025-08-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('INTRO', 'Вводный'), ('PRIMARY', 'Первичный'), ('REPEAT', 'Повторный'), ('UNSCHEDULED', 'Внеплановый')], max_length=20, verbose_name='Тип инструктажа')),
                ('training_date', models.DateField(verbose_name='Дата проведения')),
                ('next_training_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего инструктажа')),
                ('instructor', models.CharField(max_length=200, verbose_name='Инструктор')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Инструктаж',
                'verbose_name_plural': 'Инструктажи',
            },
        ),
    ]
