# Generated by Django 5.2.5 on 2025-08-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='Дата осмотра')),
                ('next_check_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего осмотра')),
                ('result', models.TextField(blank=True, verbose_name='Результаты осмотра')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Действителен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Медосмотр',
                'verbose_name_plural': 'Медосмотры',
            },
        ),
    ]
