# Generated by Django 5.2.5 on 2025-08-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Несчастный случай'), ('VIOLATION', 'Нарушение'), ('NEAR_MISS', 'Потенциальный инцидент')], max_length=20, verbose_name='Тип инцидента')),
                ('incident_date', models.DateTimeField(verbose_name='Дата и время')),
                ('description', models.TextField(verbose_name='Описание')),
                ('actions_taken', models.TextField(blank=True, verbose_name='Принятые меры')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
    ]
